# Statue Detection and Classification Configuration

# Data Configuration
data:
  raw_data_dir: "data/raw"
  processed_data_dir: "data/processed"
  results_dir: "data/results"
  train_split: 0.8
  val_split: 0.1
  test_split: 0.1
  class_map:
    other: 0
    lenin: 1
    ataturk: 2

# Model Configuration
model:
  backbone: "resnet50"
  pretrained: true
  num_classes: 3
  checkpoint_dir: "models/checkpoints"
  box_score_thresh: 0.5
  box_nms_thresh: 0.3
  box_detections_per_img: 100

# Training Configuration
train:
  device: "cuda"  # or "cpu" if GPU not available
  batch_size: 8
  num_workers: 4
  learning_rate: 0.001
  weight_decay: 0.0005
  momentum: 0.9
  epochs: 20
  log_interval: 10
  save_interval: 1
  early_stopping_patience: 5
  
  # Optimizer
  optimizer: "sgd"  # "adam", "sgd", etc.
  
  # Scheduler
  scheduler: "step"  # "step", "cosine", etc.
  scheduler_step_size: 5
  scheduler_gamma: 0.1
  
  # Logging
  log_dir: "logs"
  use_wandb: true
  wandb_project: "statue-detection"
  
  # Transforms/Augmentations
  image_size: [800, 800]
  use_augmentations: true

# Inference Configuration
inference:
  batch_size: 1
  num_workers: 2
  device: "cuda"  # or "cpu" if GPU not available